Разметка всех страниц
htmlacademy-htmlcss/341759-gllacy-36 pull request #2
Opened 2023-01-27 14:11 UTC by GusssAnna

---
:mortar_board: [Разметка всех страниц](https://up.htmlacademy.ru/htmlcss/36/user/341759/tasks/5)

2023-01-27 16:14 UTC, wrgraff requested changes
В целом очень хорошая работа, молодец )

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          </li>
Складывать логотип в список не очень то логично, потому что список это набор единообразных элементов. Ссылки на страницы довольно заметно отличаются от логотипа.

Но в самой навигации он вот вполне на своем месте

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <img class="logo" src="" alt="Логотип Gllacy Shop">
С логотипа должна быть ссылка

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <ul class="navigation-list navigation-list-catalog">
Я бы рекомендовал убрать `navigation-list`, так как этот класс совпадает с классом внешнего списка.
Кода ты пропишешь для этого класса стили, то, что они применятся сразу на оба списка тебе скорее помешает, чем поможет

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +                <a class="navigation-link navigation-link-new" href="new.html">Новинки</a>
А что, если тут будут не новинки, а "Распродажа" или "Акции"? То есть, здесь по логике может быть любая важная ссылка, которую хочется выделить.
Поэтому стоит поискать более абстрактный класс, чем `navigation-link-new`

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +                <a class="navigation-link" href="creamy.html">Сливочное</a>
Обычно ставят `#`, чтобы не переходить на несуществующие страницы по случайному клику.
Но можно и так

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          <li class="navigation-item ">
Какой-то пробел заблудился )
```suggestion
          <li class="navigation-item">
```

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +        </ul>
Напишу коммент сразу про весь блок `navigation-user`.
В демке есть 2 списка в навигации и для них используется одинаковый класс. Но важная отличительная черта сайта из демки — эти навигации там действительно похожи. Сходные размеры, отступы, расстояния. Где-то иконки есть, где-то нет — это уже опции.

Насколько схожи они в Глейси вопрос пока открытый.
Не то чтобы это прямо большая проблема будет, но держи в голове, что если что можно будет их потом разнести на совсем разные классы

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <a class="navigation-link" href="#">
Во всей навигации ссылки прописаны, а тут решетки. Может, одинаково сделаем лучше?

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          </li>
По семантике со скрытыми подписями вышло все красиво

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <a class="navigation-link navigation-telephone" href="#">+7 800 555-86-28</a>
Ну вот у телефона точно можно прописать ссылку, есть даже отдельный формат записи:
```suggestion
            <a class="navigation-link navigation-telephone" href="tel:+78005558628">+7 800 555-86-28</a>
```

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <h2 class="main-gallery-title">Нежный пломбир с клубничным джемом</h2>
Наверное, было бы красивее сделать так, чтобы у всей галереи был общий заголовок, а у каждого слайда уже — свой заголовок уровнем пониже

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <span class="basic-text">Натуральное мороженое из свежих сливок и молока с вкуснейшим клубничным джемом – это идеальный десерт для всей семьи.</span>
Чем такой большой текст провинился, что ему даже параграфа не полагается? =(

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <button class="button" type="submit">Заказать</button>
Эта кнопка — ссылка на страницу каталога с этим мороженым, где можно выбрать параметры заказа и перейти в корзину.

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          </li>
Навигационные кнопки никак не могут быть в отдельном пункте списка.
Опять же, повторюсь: список это набор идентичных элементов.

Вот если составлять список покупок для большого похода в магазин, то там будут всякие продукты и прочие вещи из супермаркета, но там не будет пункта "взять каршеринг и доехать до супермаркета", хотя это действие входит в сам по себе поход в магазин.
То есть, кнопки навигации отлично могут лежать внутри `<section>`, так как имеют к блоку самое прямое отношение, но вот список слайдов содержит только слайды.

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          </li>
Да, это сложный элемент...
Каждый слайд в разметке должен полностью содержать все, что есть в слайде.

Как это потом оживить и стилизовать под это оживление — мы подумаем потом =)

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +              <span class="visually-hidden"> Сливочное мороженое со вкусом банана</span>
Опять пробел заблудился
```suggestion
              <span class="visually-hidden">Сливочное мороженое со вкусом банана</span>
```

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +        </ol>
Пагинация классно вышла

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +      <section class="social">
Не уверен, достоин ли такой список целого блока...
Но размечен хорошо вообще-то )

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          <li>
А самой `<li>` думаешь класс не пригодится?

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <span class="basic-text">Сливочное мороженое с малиновым джемом</span>
Не стесняйся ставить параграфы даже совсем небольшим блокам текста. В разметке тег `<p>` не столько равнозначен по смыслу абзацу текста, сколько является "текстовым узлом".
По сути, любой осмысленный текст можно смело заключить в параграф

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <span class="product-card-price">310 ₽/кг</span>
Можно немного выпендриться и выделить его не в пустой по смыслу `<span>`, а например в `<strong>`, который подсказывает, что это важная информация.
Ну, если ты конечно согласна, что цена это важная информация.

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          </li>
Что-то поехало куда-то немного по тексту в кнопках.
Ну да, это мелочи, но привить к себе привычку писать код максимально аккуратно — штука полезная )

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <span class="basic-text">Всё наше мороженое изготавливается на собственном производстве с использованием современного оборудования и проверенных временем технологий.</span>
Тут или уж параграф тогда стоит проставить или сделать без спана.
`basic-text` можно поставить на сам пункт списка: я так понимаю, там будут основные стили текста у тебя, поэтому не думаю, что эти стили помешают.

Хотя, эти стили можно будет и на body кинуть... Ну это посмотрим.
В общем, логика в том, что во время разметки лучше сделать меньше элементов, чем больше. Добавить при необходимости мы всегда успеем, а вот понять, что нам что-то оказалось не нужно и убрать... Это можно и забыть )

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +      </article>
Наверное это какая-то ссылка на статью.
А вот "Новое в нашем блоге", как ни странно, по смыслу очень напоминает заголовок.

А почему тут `article`? Потому что статья? =)

Но `article` по семантике не обозначает статью, он обозначает законченный по смыслу блок, достаточно самостоятельный, чтобы его можно было использовать вне контекста сайта (отчуждаемый, так сказать).
То есть, это как `section`, но можно его поставить на другой сайт — и будет логично.

Таким блоком может быть, например, карточка товара. Или анонс новости.
Тут вроде бы с одной стороны логика подходит, но вообще это просто ссылка на статью и больше ничего. Как-то мелковато, что ли

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          <input class="field"  placeholder="email@example.com" type="email" name="newsletter-email" id="newsletter-email" required>
```suggestion
          <input class="field" placeholder="email@example.com" type="email" name="newsletter-email" id="newsletter-email" required>
```

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <span class="button button-pink">Отправить</span>
Так у нас получилась кнопка внутри кнопки.
Постарайся оставить одну (если хочешь на ней все 3 доп класса сохранить — почему бы и нет, кто нам запретит?)

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +        <p>Укажите адрес и дату доставки, и мы свяжемся с вами, чтобы подтвердить заказ.</p>
Ура! Параграфы! 😄

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +            <input type="text" id="delivery-phone" name="delivery-phone" placeholder="+7 800 999-00-00">
А есть специальный тип поля для телефонов (кстати, для даты тоже есть, но стоит подумать ставить ли его — там твой плейсхолдер затрется стандартным и могут быть проблемы на защите из-за несоответствия макету. Хотя я бы такое пропускал)

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          <p class="delivery-form-address">
Смотри, кроме размеров по ширине `delivery-form-date`, `delivery-form-phone` и `delivery-form-address` ничем не различаются.
Можно им какой-то общий класс накинуть, чтобы стилизовать поля и лейблы сразу по нему.

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +        </h2>
Не, `visually-hidden` надо на сам заголовок поставить, чтобы его скрыть =) А то он будет в разметке болтаться и мешать нам.
Внутрь это мы спан кладем тогда, когда хотим чтобы элемент был виден, а текст внутри — нет. Обычно это интерактивные элементы такие (но не всегда!).

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +              <a class="navigation-link navigation-link-suppliers" href="#">Для поставщиков</a>
Опять же, пункт имеет особый вид визуально. Но там вообще сердечко, поэтому так можно отметить не только поставщиков.
Можно даже написать `navigation-link-heart`, так понятно, что оно добавит сердечко =)

2023-01-27 16:14 UTC, wrgraff commented on index.html
> +          <img class="htmlacademy-logo" src="" alt="Логотип htmlacademy">
Здесь картинка как-то смысла не добавляет, потому что текст ниже уже содержит упоминание компании.
Я бы его в декоративные элементы отнес.

2023-01-27 16:14 UTC, wrgraff commented on catalog.html
> +    <main class="main-inter">
`<main>` — один из трех основных блоков страницы, вместе с хэдером и футером.
Лучше не делать его разным на разных страницах, он должен быть как основа, как фундамент для контента каждой страницы.

2023-01-27 16:14 UTC, wrgraff commented on catalog.html
> +      <header class="inner-header">
А вот внутри мейна выделить отдельный заголовочный блок для внутренних страниц — это сколько угодно )

2023-01-27 16:14 UTC, wrgraff commented on catalog.html
> +        <h2 class="visually-hidden">Список товаров с фильтрами</h2>
Может, нам отдельно фильтры, отдельно список сделать? Они тут так удобно последовательно идут

2023-01-27 16:14 UTC, wrgraff commented on catalog.html
> +          <h3 class="select-control-title">Сортировка</h3>
В `<select>` не может быть заголовка )
В нем только свои специфические элементы должны быть

2023-01-27 16:14 UTC, wrgraff commented on catalog.html
> +          <h3 class="select-control-title">Сортировка</h3>
А еще это тоже элемент формы. И у него должен быть лейбл как и у всех инпутов

2023-01-27 16:14 UTC, wrgraff commented on catalog.html
> +        <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">
А почему селект выпал из формы?

2023-01-27 16:14 UTC, wrgraff commented on catalog.html
> +        </form>
А где слайдер с ценой? Вам пока разрешили его не размечать?

2023-01-27 16:14 UTC, wrgraff commented on catalog.html
> +        <button class="visually-hidden" type="button">Пустота</button>
О_о
Какая такая пустота

2023-01-28 18:23 UTC, GusssAnna commented on index.html
> +          </li>
Поправила

2023-01-28 18:29 UTC, GusssAnna commented on index.html
> +            <img class="logo" src="" alt="Логотип Gllacy Shop">
я конечно поставила ссылку, но это же главная страница и с логотипа некуда вести)

2023-01-28 18:31 UTC, GusssAnna commented on index.html
> +            <ul class="navigation-list navigation-list-catalog">
Убрала

2023-01-28 18:35 UTC, GusssAnna commented on index.html
> +                <a class="navigation-link navigation-link-new" href="new.html">Новинки</a>
Поправила

2023-01-28 18:36 UTC, GusssAnna commented on index.html
> +          <li class="navigation-item ">
поправила

2023-01-28 18:38 UTC, GusssAnna commented on index.html
> +                <a class="navigation-link" href="creamy.html">Сливочное</a>
В обучалке сказано было так ставить, я вообще тоже не поняла зачем( ну и исправлять не слала, все равно скоро там ссылку сделаем) а если не сделаем то поставлю диез)

2023-01-28 18:40 UTC, GusssAnna commented on index.html
> +        </ul>
записала себе)

2023-01-28 18:42 UTC, GusssAnna commented on index.html
> +            <a class="navigation-link" href="#">
Поправила

2023-01-28 18:46 UTC, GusssAnna commented on index.html
> +            <a class="navigation-link navigation-telephone" href="#">+7 800 555-86-28</a>
поправила

2023-01-28 18:50 UTC, GusssAnna commented on index.html
> +            <h2 class="main-gallery-title">Нежный пломбир с клубничным джемом</h2>
Поправила

2023-01-28 18:53 UTC, GusssAnna commented on index.html
> +            <span class="basic-text">Натуральное мороженое из свежих сливок и молока с вкуснейшим клубничным джемом – это идеальный десерт для всей семьи.</span>
поправила

2023-01-28 18:58 UTC, GusssAnna commented on index.html
> +            <button class="button" type="submit">Заказать</button>
поправила

2023-01-28 19:01 UTC, GusssAnna commented on index.html
> +          </li>
Поправила

2023-01-28 19:13 UTC, GusssAnna commented on index.html
> +          </li>
поправила

2023-01-28 19:13 UTC, GusssAnna commented on index.html
> +              <span class="visually-hidden"> Сливочное мороженое со вкусом банана</span>
Поправила

2023-01-28 19:17 UTC, GusssAnna commented on index.html
> +          <li>
поправила

2023-01-28 19:24 UTC, GusssAnna commented on index.html
> +            <span class="basic-text">Сливочное мороженое с малиновым джемом</span>
поправила, мой косяк, сначала везде прописала <p> а потом решила косяк и исправила(((

2023-01-28 19:27 UTC, GusssAnna commented on index.html
> +            <span class="product-card-price">310 ₽/кг</span>
поправила

2023-01-28 19:27 UTC, GusssAnna commented on index.html
> +          </li>
поправила

2023-01-28 19:33 UTC, GusssAnna commented on index.html
> +            <span class="basic-text">Всё наше мороженое изготавливается на собственном производстве с использованием современного оборудования и проверенных временем технологий.</span>
<span> заменила на <p>, пока класс basic-text не буду убирать, так как он у меня прописан везде где одинаковый текст, если не пригодиться то пройдусь и удалю его во всем документе) Надеюсь, ты не против)

2023-01-28 19:46 UTC, GusssAnna commented on index.html
> +      </article>
Поправила заголовок, сделала ссылкой, по article ничего не правила, так как в учебном материале этот блок article

2023-01-28 19:47 UTC, GusssAnna commented on index.html
> +          <input class="field"  placeholder="email@example.com" type="email" name="newsletter-email" id="newsletter-email" required>
поправила

2023-01-28 19:55 UTC, GusssAnna commented on index.html
> +            <span class="button button-pink">Отправить</span>
поправила, вот говорят же списывать не хорошо))) списала с обучалки)))

2023-01-28 20:32 UTC, GusssAnna commented on index.html
> +            <input type="text" id="delivery-phone" name="delivery-phone" placeholder="+7 800 999-00-00">
я поправила, но в обучалке именно так просили сделать, наверно для того что бы потом поправить)

2023-01-28 20:35 UTC, GusssAnna commented on index.html
> +          <p class="delivery-form-address">
добавила)

2023-01-28 20:36 UTC, GusssAnna commented on index.html
> +        </h2>
ага, я тупанула(((

2023-01-28 20:38 UTC, GusssAnna commented on index.html
> +              <a class="navigation-link navigation-link-suppliers" href="#">Для поставщиков</a>
поправила)

2023-01-28 20:40 UTC, GusssAnna commented on index.html
> +          <img class="htmlacademy-logo" src="" alt="Логотип htmlacademy">
Поправила

2023-01-28 20:42 UTC, GusssAnna commented on catalog.html
> +    <main class="main-inter">
поправила

2023-01-28 20:48 UTC, GusssAnna commented on catalog.html
> +        <h2 class="visually-hidden">Список товаров с фильтрами</h2>
поправила

2023-01-28 20:50 UTC, GusssAnna commented on catalog.html
> +          <h3 class="select-control-title">Сортировка</h3>
готово

2023-01-28 20:52 UTC, GusssAnna commented on catalog.html
> +        <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">
поправила

2023-01-28 20:53 UTC, GusssAnna commented on catalog.html
> +        </form>
Да, сказали позже его очень подробно разберут и мы добавим

2023-01-29 21:13 UTC, wrgraff commented on index.html
> +        </a>
А чего вложенность съехала? =)

2023-01-29 21:13 UTC, wrgraff commented on index.html
> +            <img class="logo" src="" alt="Логотип Gllacy Shop">
Как раз так и делается обычно. Чтобы разметка была на всех страницах единообразной, логотип везде будет в ссылке.
Но без атрибута href ссылка не будет никак работать

2023-01-29 21:34 UTC, wrgraff commented on index.html
> +                <a class="navigation-link" href="creamy.html">Сливочное</a>
Не знаю, звучит странно.
А что именно за обучалка? Тренажеры, статьи, лекции?..

2023-01-29 21:34 UTC, wrgraff commented on index.html
> +            <a class="navigation-link" href="input.html">Вход</a>
```suggestion
            <a class="navigation-link" href="login.html">Вход</a>
```

2023-01-29 21:34 UTC, wrgraff commented on index.html
> +        <h2 class="main-gallery-title">Галирея мороженого</h2>
```suggestion
        <h2 class="main-gallery-title">Галерея мороженого</h2>
```

2023-01-29 21:34 UTC, wrgraff commented on index.html
> +        <h2 class="main-gallery-title">Галирея мороженого</h2>
Наверное это должен быть скрытый заголовок? )

2023-01-29 21:34 UTC, wrgraff commented on index.html
> +          <li class="popular-product-item">
По-моему, и карточка популярных продуктов и просто продуктов одинакова будет. Соответственно, логично их одинаково разметить

2023-01-29 21:34 UTC, wrgraff commented on index.html
>            </li>
Я так и не понял — а почему нельзя так?

```html
<li class="advantages-item basic-text">
  Доставка нашего мороженого осуществляется в специальном термопаке, который не даёт мороженому растаять и позволяет сохранить превосходный вкус.
</li>
```

2023-01-29 21:34 UTC, wrgraff commented on index.html
> +        <a class="blog-advertising" href="blog.html">
Имел ввиду сделать ссылку вместо `<h3>`.
Заголовки нужна чтобы что-то озаглавить. А тут получается заголовков 2, а контента вообще нет

2023-01-29 21:34 UTC, wrgraff commented on index.html
> +            <input type="tel" id="tel" name="tel" pattern="[0-9]{1} [0-9]{3} [0-9]{3}[0-9]{2}[0-9]{2}" placeholder="8 800 9990000">
С паттерном нужно быть осторожнее. Что, если это телефон другого формата? Если его захотят записать иначе, почему мы диктуем пользователю формат?

2023-01-29 21:34 UTC, wrgraff commented on index.html
> +            <input type="text" id="delivery-phone" name="delivery-phone" placeholder="+7 800 999-00-00">
А чем мотивировали?

2023-01-29 21:34 UTC, wrgraff commented on catalog.html
> +      <section class="catalog-product">
Ммм, а заголовок для секции с товарами?
Надо бы добавить

2023-01-29 21:34 UTC, wrgraff commented on catalog.html
> +        </form>
Может, вместо него какой-то банальный инпут придется поставить, чтобы сетку делать с учетом того, что тут что-то будет

2023-01-29 21:35 UTC, wrgraff requested changes
Одна маленькая обязательная правка есть )

2023-01-29 21:43 UTC, GusssAnna commented on index.html
> +                <a class="navigation-link" href="creamy.html">Сливочное</a>
В видошке, сказали что бы не забыть там поставить ссылку)

2023-01-29 21:45 UTC, GusssAnna commented on index.html
> +            <input type="text" id="delivery-phone" name="delivery-phone" placeholder="+7 800 999-00-00">
ничем

2023-01-30 08:16 UTC, wrgraff commented on index.html
> +                <a class="navigation-link" href="creamy.html">Сливочное</a>
Так может речь шла про ссылку на страницу каталога — единственную страницу, которая у нас в проекте действительно будет (кроме главной)?

2023-01-30 08:17 UTC, wrgraff commented on index.html
> +            <input type="text" id="delivery-phone" name="delivery-phone" placeholder="+7 800 999-00-00">
Странное конечно =)

2023-01-30 08:22 UTC, GusssAnna commented on catalog.html
> +        </form>
добавила

2023-01-30 08:26 UTC, GusssAnna commented on index.html
> +            <a class="navigation-link" href="input.html">Вход</a>
В видео по разбору разметки барбершопа

2023-01-30 08:27 UTC, GusssAnna commented on index.html
> +        <h2 class="main-gallery-title">Галирея мороженого</h2>
Поправила

2023-01-30 08:28 UTC, GusssAnna commented on index.html
> +        <h2 class="main-gallery-title">Галирея мороженого</h2>
поправила

2023-01-30 08:32 UTC, GusssAnna commented on index.html
> +          <li class="popular-product-item">
поправила

2023-01-30 08:36 UTC, GusssAnna commented on index.html
>            </li>
ну тут скорее я не знала что так можно было))) поправила

2023-01-30 08:43 UTC, GusssAnna commented on index.html
> +            <input type="tel" id="tel" name="tel" pattern="[0-9]{1} [0-9]{3} [0-9]{3}[0-9]{2}[0-9]{2}" placeholder="8 800 9990000">
убрала паттерн

2023-01-30 08:51 UTC, GusssAnna commented on catalog.html
> +      <section class="catalog-product">
поправила

2023-01-30 08:52 UTC, GusssAnna commented on index.html
> +        <a class="blog-advertising" href="blog.html">
поправила

2023-01-30 08:59 UTC, wrgraff approved these changes

2023-01-30 09:09 UTC, wrgraff commented on catalog.html
> +          -->
Закомментированный код лучше не отправлять в пул-реквесте.
Я имел ввиду, прям вот добавить живой элемент, чтобы мы сам элемент в сетку встроили. А потом уже его переделать по инструкции

2023-01-30 09:09 UTC, merged