Добавляет шрифтовые стили
htmlacademy-htmlcss/341759-gllacy-36 pull request #4
Opened 2023-02-13 09:30 UTC by GusssAnna

2023-02-14 08:50 UTC, wrgraff requested changes

2023-02-14 08:50 UTC, wrgraff commented on index.html
> +          <li class="advantages-item-ice-cream basic-text">
А почему вот эти классы ты добавила к основному: `<li class="gifts-item gifts-item-raspberry">`
а тут заменила основной: `<li class="advantages-item-ice-cream basic-text">` ?

Лучше всегда добавлять, это удобно: основные стили через общий класс, а картинки через дополнительный можно будет ставить:
```suggestion
          <li class="advantages-item advantages-item-ice-cream basic-text">
```

2023-02-14 08:50 UTC, wrgraff commented on index.html
> +      <div class="benefits">
Обычно обертку добавляют вовнутрь и сохраняют для нее пространство имен, то есть делают какой-нибудь `advantages-container`.

2023-02-14 08:50 UTC, wrgraff commented on index.html
> +      <div class="benefits">
Ну и если добавила обертку, то форматирование кода тоже надо обязательно поправить: все что вложено должно сдвинуться на один шаг вправо.

2023-02-14 08:50 UTC, wrgraff commented on index.html
>          <span class="basic-text">Подпишитесь на нашу сладкую рассылку и будьте всегда в курсе всего самого вкусного, что у нас происходит. Обещаем не спамить и не слать всякой ненужной ерунды. Честно
Просмотрел ранее: такой крупный блок текста лучше бы конечно в параграф превратить

2023-02-14 08:50 UTC, wrgraff commented on index.html
> +       <div class="delivery-all-form">
Тут форматирование что-то еще страньше стало )

2023-02-14 08:50 UTC, wrgraff commented on catalog.html
> +          <label class="catalog-filter-title">Сортировка
А почему тут ты в лейбл оборачиваешь, а в форме доставки нет? =)
Хотя, я знаю почему это может быть полезно с нашим макетом. А ты? ))

2023-02-14 08:50 UTC, wrgraff commented on styles/styles.css
> +}
Опять с форматированием что-то =Р

2023-02-14 08:50 UTC, wrgraff commented on styles/styles.css
> +  font-family: 'inter' sans-serif;
Тут должна быть запятая, такое значение не валидно
```suggestion
  font-family: 'inter', sans-serif;
```

2023-02-14 08:50 UTC, wrgraff commented on styles/styles.css
> +  font-family: 'inter' sans-serif;
А зачем ты вообще прописываешь здесь (и в других местах) `font-family`?
Он же спокойно наследуется в ссылки, заголовки и прочее.

Единственное, куда не наследуется — это всякие элементы форм, вроде инпутов и кнопок. И то я бы рекомендовал там писать `font-family: inherit;`, чтобы если что-то понадобится поменять, это приходилось делать в одном месте (то есть мы как бы меняем не шрифт, а делаем его наследуемым).

2023-02-14 08:50 UTC, wrgraff commented on styles/styles.css
> +  text-align: left;
Не понял зачем выравнивание по левому краю, оно же по умолчанию и так по левому краю

2023-02-14 08:50 UTC, wrgraff commented on styles/styles.css
> +.popular-product {
Следи за форматированием повнимательнее =)

2023-02-14 08:50 UTC, wrgraff commented on styles/styles.css
> +.benefits{
```suggestion
.benefits {
```

2023-02-14 08:50 UTC, wrgraff commented on styles/styles.css
> +}
Вот тут как раз в основной класс бы вынести все стили повторяющиеся.
```css
.advantages-item {
  background-size: 24px 24px;
  background-repeat: no-repeat;
}

.advantages-item-ice-cream {
  background-image: url("../images/ice_cream.svg");
}

.advantages-item-sheet {
  background-image: url("../images/sheet.svg");
}

.advantages-item-cow {
  background-image: url("../images/cow.svg");
}

.advantages-item-thermometer {
  background-image: url("../images/thermometer.svg");
}
```

2023-02-14 08:50 UTC, wrgraff commented on styles/styles.css
> +/* Стили каталога */
Почему каталога )
Вон, `.inner-header` может быть и на других страницах

2023-02-15 07:44 UTC, GusssAnna commented on index.html
> +          <li class="advantages-item-ice-cream basic-text">
поправила

2023-02-15 08:01 UTC, GusssAnna commented on index.html
> +      <div class="benefits">
поправила

2023-02-15 08:05 UTC, GusssAnna commented on index.html
>          <span class="basic-text">Подпишитесь на нашу сладкую рассылку и будьте всегда в курсе всего самого вкусного, что у нас происходит. Обещаем не спамить и не слать всякой ненужной ерунды. Честно
поправила

2023-02-15 08:11 UTC, GusssAnna commented on catalog.html
> +          <label class="catalog-filter-title">Сортировка
я для чего-то это делала, но уже не помню) если будет проще в лейбл обернуть то позже оберну))

2023-02-15 08:12 UTC, GusssAnna commented on styles/styles.css
> +}
поправила

2023-02-15 08:15 UTC, GusssAnna commented on styles/styles.css
> +  font-family: 'inter' sans-serif;
поправила

2023-02-15 08:23 UTC, GusssAnna commented on styles/styles.css
> +  font-family: 'inter' sans-serif;
готово

2023-02-15 08:24 UTC, GusssAnna commented on styles/styles.css
> +  text-align: left;
поправила

2023-02-15 08:25 UTC, GusssAnna commented on styles/styles.css
> +.popular-product {
поправила

2023-02-15 08:26 UTC, GusssAnna commented on styles/styles.css
> +.benefits{
готово

2023-02-15 08:33 UTC, GusssAnna commented on styles/styles.css
> +}
поправила

2023-02-15 08:34 UTC, GusssAnna commented on styles/styles.css
> +/* Стили каталога */
это для себя пока, я потом удалю))

2023-02-15 08:35 UTC, GusssAnna commented on styles/styles.css
> +/* Стили каталога */
там имеется введу стили что со страницы каталога дальше идут)

2023-02-15 08:47 UTC, GusssAnna commented on index.html
> +       <div class="delivery-all-form">
поправила

2023-02-15 20:57 UTC, wrgraff commented on styles/styles.css
> +/* Стили каталога */
Я понял что имеется ввиду, но стили по страницам лучше не делить.
Можно по секциям, например. Потому что они могут переиспользоваться на разных страницах

2023-02-15 20:59 UTC, wrgraff commented on catalog.html
> +          <label class="catalog-filter-title">Сортировка
Там иконка "инфо", и ее лучше не оборачивать в лейбл, так как она отдельный интерактивный элемент.
Поэтому тут может так и удобнее

2023-02-15 21:00 UTC, wrgraff approved these changes

2023-02-15 21:00 UTC, merged